In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[['Kecamatan Pademangan' 'Ciu' 19]
 ['Kecamatan Pademangan' 'Anggur Orang Tua' 134]
 ['Kecamatan Pademangan' 'Guinnes' 12]
 ['Kecamatan Pademangan' 'Anggur Merah' 84]
 ['Kecamatan Pademangan' 'Rajawali' 84]
 ['Kecamatan Pademangan' 'Vodka' 4]
 ['Kecamatan Pademangan' 'Intisari' 9]
 ['Kecamatan Koja' 'Anggur Orang Tua' 13]
 ['Kecamatan Koja' 'Anggur Merah' 2]
 ['Kecamatan Koja' 'Brandy' 60]
 ['Kecamatan Koja' 'Mansion' 23]
 ['Kecamatan Koja' 'Rajawali' 55]
 ['Kecamatan Koja' 'Anggur Ginseng' 132]
 ['Kecamatan Koja' 'Vodka' 20]
 ['Kecamatan Cilincing' 'Anggur Merah' 9]
 ['Kecamatan Cilincing' 'Brandy' 181]
 ['Kecamatan Cilincing' 'Rajawali' 26]
 ['Kecamatan Cilincing' 'Kolesom Kecil' 9]
 ['Kecamatan Cilincing' 'Kolesom Besar' 10]
 ['Kecamatan Cilincing' 'Aseng' 41]
 ['KecamatanTanjung Priok' 'Brandy' 60]
 ['KecamatanTanjung Priok' 'Rajawali' 45]
 ['KecamatanTanjung Priok' 'Intisari' 3]
 ['Kecamatan Kelapa Gading' 'Guinnes' 5]
 ['Kecamatan Kelapa Gading' 'Bintang' 42]
 ['Kecamatan Kelapa 

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print (x)

[[0.0 0.0 0.0 1.0 0.0 'Ciu' 19]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Orang Tua' 134]
 [0.0 0.0 0.0 1.0 0.0 'Guinnes' 12]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Merah' 84]
 [0.0 0.0 0.0 1.0 0.0 'Rajawali' 84]
 [0.0 0.0 0.0 1.0 0.0 'Vodka' 4]
 [0.0 0.0 0.0 1.0 0.0 'Intisari' 9]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Orang Tua' 13]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Merah' 2]
 [0.0 0.0 1.0 0.0 0.0 'Brandy' 60]
 [0.0 0.0 1.0 0.0 0.0 'Mansion' 23]
 [0.0 0.0 1.0 0.0 0.0 'Rajawali' 55]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Ginseng' 132]
 [0.0 0.0 1.0 0.0 0.0 'Vodka' 20]
 [1.0 0.0 0.0 0.0 0.0 'Anggur Merah' 9]
 [1.0 0.0 0.0 0.0 0.0 'Brandy' 181]
 [1.0 0.0 0.0 0.0 0.0 'Rajawali' 26]
 [1.0 0.0 0.0 0.0 0.0 'Kolesom Kecil' 9]
 [1.0 0.0 0.0 0.0 0.0 'Kolesom Besar' 10]
 [1.0 0.0 0.0 0.0 0.0 'Aseng' 41]
 [0.0 0.0 0.0 0.0 1.0 'Brandy' 60]
 [0.0 0.0 0.0 0.0 1.0 'Rajawali' 45]
 [0.0 0.0 0.0 0.0 1.0 'Intisari' 3]
 [0.0 1.0 0.0 0.0 0.0 'Guinnes' 5]
 [0.0 1.0 0.0 0.0 0.0 'Bintang' 42]
 [0.0 1.0 0.0 0.0 0.0 'Bir' 66]
 [0.0 1.0 0.0 0.0 0.0 'Angg

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [18]:
print(x_train)

[[1.0 0.0 1.0 0.0 0.0 0.0 'Anggur Merah' 120]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Anggur Merah' 84]
 [1.0 0.0 1.0 0.0 0.0 0.0 'Bintang' 42]
 [1.0 0.0 0.0 0.0 0.0 1.0 'Intisari' 3]
 [1.0 0.0 1.0 0.0 0.0 0.0 'Guinnes' 5]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Rajawali' 84]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Guinnes' 12]
 [1.0 0.0 1.0 0.0 0.0 0.0 'Bir' 66]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Intisari' 9]
 [0.0 1.0 0.0 0.0 0.0 0.0 'Kolesom Besar' 10]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Vodka' 20]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Anggur Orang Tua' 13]
 [1.0 0.0 1.0 0.0 0.0 0.0 'Brandy' 60]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Anggur Orang Tua' 134]
 [0.0 1.0 0.0 0.0 0.0 0.0 'Rajawali' 26]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Ciu' 19]
 [0.0 1.0 0.0 0.0 0.0 0.0 'Brandy' 181]
 [1.0 0.0 1.0 0.0 0.0 0.0 'Bir Hitam' 119]
 [1.0 0.0 1.0 0.0 0.0 0.0 'Vodka' 4]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Brandy' 60]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Anggur Merah' 2]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Anggur Ginseng' 132]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Rajawali' 55]
 [1.0 0.0 0.0 0.0 1.0 0.0 'Vodka' 4]]


In [19]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 'Kolesom Kecil' 9]
 [1.0 0.0 0.0 0.0 0.0 1.0 'Rajawali' 45]
 [1.0 0.0 0.0 1.0 0.0 0.0 'Mansion' 23]
 [0.0 1.0 0.0 0.0 0.0 0.0 'Aseng' 41]
 [0.0 1.0 0.0 0.0 0.0 0.0 'Anggur Merah' 9]
 [1.0 0.0 0.0 0.0 0.0 1.0 'Brandy' 60]]


In [20]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [21]:
print(y_test)

[0 0 0 0 0 0]


In [ ]:
from sklearn.preprocessing import StandartScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])